server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}